### ISSUE TITLE
[ENTREGA DE RECUPERATORIO] Pilar Vilaplana

### ISSUE THREAD

**Issue by PVilaplana** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-PVilaplana#1]
Entrega de recuperatorio Objetos

Juan Fernandes  @juanFdS

**Comment by JuanFdS** [comment]
"## Parte A
### Punto 1
❌ El mago no conoce los objetos mágicos que tiene equipados (según la consigna puede ser más de uno), por lo tanto el poder total no puede calcularse con esta implementación.
❌ La implementación de algunos objetos en sí es incorrecta, como las túnicas épicas (no hay una condición según la consigna).
### Punto 2
❌ ¿Por qué un mago recibe dos magos más por parámetro al desafiar? ¿No debería él desafiar a uno solo?
❌ La implementación de `ganaBatalla` está incompleta.
## Parte B
### Punto 1
✅ Bien la validación del nro. de miembros...
❌ Pero al gremio se le pasan otras variables internas al crearlo que no deberían pasarse. Concretamente, la reserva de energía y la resistencia mágica se calculan a partir de los miembros, no deberían ser variables internas independientes.
### Punto 2
❌ Incompleto.
### Punto 3
❌ Incompleto.
## Tests
N/A,

---------------------

Nota: 2
